[package]
name = "rubenvy"
description = "Support for Ruby-style dotenv loading priorities utilizing dotenvy."
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/swlody/rubenvy"

[dependencies]
dotenvy = "0.15.7"
